export const UserConstants = {
  FETCH_ALL_USERS: "FETCH_ALL_USERS",
  RECEIVE_ALL_USERS: "RECEIVE_ALL_USERS",
  RECEIVE_ERRORS: "RECEIVE_ERRORS",
  RECEIVE_SINGLE_USER: "RECEIVE_SINGLE_USER",
  GO_TO_PROFILE: "GO_TO_PROFILE"
};

export const fetchAllUsers = () => ({
  type: UserConstants.FETCH_ALL_USERS
});
